nameOverride: ""
fullnameOverride: ""

workload:
  enabled: true
  type: Deployment
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  podAnnotations: {}
  podLabels: {}
  terminationGracePeriodSeconds: null

image:
  repository: nginx
  tag: stable-alpine
  pullPolicy: IfNotPresent
  pullSecrets:
    - name: nexus

container:
  name: ""
  command: []
  args: []
  ports:
    - name: http
      containerPort: 80
      protocol: TCP
  env:
    plain: {}
    valueFrom: []
    fromSecrets: []
    fromConfigMaps: []
  envFrom:
    configMaps: []
    secrets: []

initContainers: []

probes:
  startup:
    enabled: false
    periodSeconds: 10
    failureThreshold: 6
    httpGet: null
    exec: null
  liveness:
    enabled: false
    periodSeconds: 60
    initialDelaySeconds: 60
    httpGet: null
    exec: null

resources: {}

configMaps:
  create: false
  data: {}

secrets:
  create: false
  type: Opaque
  data: {}
  stringData: {}

volumes:
  pvc:
    create: false
    claims: []
  existing: []

service:
  enabled: false
  type: ClusterIP
  annotations: {}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts: []
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: null
  targetMemoryUtilizationPercentage: null

serviceMonitor:
  enabled: false
  labels:
    release: rancher-monitoring
  path: /metrics
  interval: 30s
  scrapeTimeout: 10s

scheduling:
  nodeSelector: {}
  tolerations: []
  affinity: {}

cronJobs: []
