fullnameOverride: app-v2

workload:
  enabled: true
  type: Deployment
  replicas: 2

image:
  repository: nginx
  tag: stable-alpine
  pullPolicy: IfNotPresent
  pullSecrets:
    - name: nexus

container:
  ports:
    - name: http
      containerPort: 80
      protocol: TCP
  env:
    plain:
      X_ENV: abc
  envFrom:
    configMaps:
      - shared-config

configMaps:
  create: true
  data:
    CONFIG: config

service:
  enabled: true
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP

ingress:
  enabled: true
  hosts:
    - host: app-v2.example.com
      paths:
        - path: /app
          pathType: Prefix
          servicePort: http

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

scaledObject:
  enabled: true
  minReplicaCount: 1
  maxReplicaCount: 4
  pollingInterval: 30
  cooldownPeriod: 120
  triggers:
    - type: rabbitmq
      metadata:
        queueName: queue
        host: amqp://admin:admin@localhost:5672
        queueLength: "20"
    - type: cron
      metadata:
        start: 0 19 * * 1-5
        end: 0 21 * * 1-5
        desiredReplicas: "3"
