{{- if .Values.cronJobs }}
{{- $root := . -}}
{{- range $k, $job := .Values.cronJobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $job.name }}
  namespace: {{ $root.Release.Namespace }}
spec:
  schedule: {{ $job.schedule | quote }}
  concurrencyPolicy: {{ $job.backoffLimit }}
  successfulJobsHistoryLimit: {{ $job.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ $job.failedJobsHistoryLimit }}
  jobTemplate:
    backoffLimit: {{ $job.backoffLimit }}
    activeDeadlineSeconds: {{ $job.activeDeadlineSeconds }}
    spec:
      template:
        spec:
          restartPolicy: {{ $job.restartPolicy }}
          containers:
            - name: {{ $job.name }}
              image: {{ $job.image }}
              {{- if $job.command }}
              command:
                {{ toYaml $job.command.cmd | nindent 16 | trim }}
              {{- end }}
---
{{- end }}
{{- end }}
