{{- if and (eq (include "helm_template.workloadEnabled" .) "true") (eq (include "helm_template.workloadType" .) "Deployment") }}
{{- $workload := default dict .Values.workload -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm_template.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "helm_template.labels" . | indent 4 }}
spec:
  replicas: {{ include "helm_template.replicas" . }}
  revisionHistoryLimit: {{ include "helm_template.revisionHistoryLimit" . }}
  selector:
    matchLabels:
{{ include "helm_template.selectorLabels" . | indent 6 }}
  strategy:
{{- if $workload.strategy }}
{{ toYaml $workload.strategy | indent 4 }}
{{- else }}
    type: {{ default "RollingUpdate" .Values.rolloutStrategy.type }}
{{- if eq (default "RollingUpdate" .Values.rolloutStrategy.type) "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ default "25%" .Values.rolloutStrategy.maxSurge }}
      maxUnavailable: {{ default "25%" .Values.rolloutStrategy.maxUnavailable }}
{{- end }}
{{- end }}
  template:
    metadata:
{{ include "helm_template.podMetadata" . | indent 6 }}
    spec:
{{ include "helm_template.podSpec" . | indent 6 }}
{{- end }}
