{{- $ingress := default dict .Values.ingress -}}
{{- if $ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helm_template.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "helm_template.labels" . | indent 4 }}
{{- if or $ingress.annotations $ingress.tls }}
  annotations:
{{- if and $ingress.caIssuer (not $ingress.hosts) }}
    cert-manager.io/cluster-issuer: {{ $ingress.caIssuer | quote }}
    cert-manager.io/common-name: {{ $ingress.dns | quote }}
{{- end }}
{{- with $ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
spec:
  ingressClassName: {{ default "nginx" $ingress.className }}
{{- if $ingress.tls }}
  tls:
{{- if kindIs "bool" $ingress.tls }}
    - hosts:
        - {{ $ingress.dns }}
      secretName: {{ $ingress.dns }}-tls
{{- else }}
{{ toYaml $ingress.tls | indent 4 }}
{{- end }}
{{- end }}
  rules:
{{- if $ingress.hosts }}
{{- range $host := $ingress.hosts }}
    - host: {{ $host.host }}
      http:
        paths:
{{- range $path := $host.paths }}
          - path: {{ $path.path }}
            pathType: {{ default "Prefix" $path.pathType }}
            backend:
              service:
                name: {{ default (include "helm_template.fullname" $) $path.serviceName }}
                port:
                  {{- if kindIs "string" (default "http" $path.servicePort) }}
                  name: {{ default "http" $path.servicePort }}
                  {{- else }}
                  number: {{ default 80 $path.servicePort }}
                  {{- end }}
{{- end }}
{{- end }}
{{- else }}
    - host: {{ $ingress.dns }}
      http:
        paths:
{{- range $path := $ingress.paths }}
          - path: {{ $path.path }}
            pathType: {{ default "Prefix" $path.pathType }}
            backend:
              service:
                name: {{ default (include "helm_template.fullname" $) $path.serviceName }}
                port:
                  number: {{ default $.Values.service.port $path.servicePort }}
{{- end }}
{{- end }}
{{- end }}
