{{- $secrets := default dict .Values.secrets -}}
{{- if or $secrets.create $secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm_template.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "helm_template.labels" . | indent 4 }}
type: {{ default "Opaque" $secrets.type }}
{{- if $secrets.data }}
data:
{{- range $key, $val := $secrets.data }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
{{- end }}
{{- if $secrets.stringData }}
stringData:
{{ toYaml $secrets.stringData | indent 2 }}
{{- end }}
{{- end }}
