{{- $service := default dict .Values.service -}}
{{- if $service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm_template.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "helm_template.labels" . | indent 4 }}
{{- if $service.annotations }}
  annotations:
{{ toYaml $service.annotations | indent 4 }}
{{- end }}
spec:
  ports:
{{- if and $service.port $service.targetPort }}
    - name: http
      port: {{ default 80 $service.port }}
      protocol: {{ default "TCP" $service.protocol }}
      targetPort: {{ default (default 80 $service.port) $service.targetPort }}
{{- else if $service.ports }}
{{ toYaml $service.ports | indent 4 }}
{{- else }}
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
{{- end }}
  selector:
{{ include "helm_template.selectorLabels" . | indent 4 }}
  sessionAffinity: None
  type: {{ default "ClusterIP" $service.type }}
{{- end }}
