{{- if and (eq (include "helm_template.workloadEnabled" .) "true") (eq (include "helm_template.workloadType" .) "StatefulSet") }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "helm_template.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "helm_template.labels" . | indent 4 }}
spec:
  replicas: {{ include "helm_template.replicas" . }}
  revisionHistoryLimit: {{ include "helm_template.revisionHistoryLimit" . }}
  serviceName: {{ include "helm_template.fullname" . }}
  selector:
    matchLabels:
{{ include "helm_template.selectorLabels" . | indent 6 }}
  template:
    metadata:
{{ include "helm_template.podMetadata" . | indent 6 }}
    spec:
{{ include "helm_template.podSpec" . | indent 6 }}
{{- end }}
